"""ORCA input file compiler - single-job chain fusion."""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, Set


class MoleculeLike(Protocol):
    """Protocol for molecule-like objects."""
    atoms: str
    charge: int
    multiplicity: int


class ORCAInputCompiler:
    """
    Compiles a QCChain into a single ORCA input file.

    MVP: No $new_job, single job with fused keywords/blocks.
    All steps in a chain are combined into one ORCA input.
    """

    def compile(
        self,
        chain: Any,  # QCChain
        molecule: MoleculeLike,
        fresh: bool = False,
        nprocs: Optional[int] = None,
    ) -> str:
        """
        Compile chain to ORCA input string.

        Args:
            chain: QCChain to compile
            molecule: Molecule with atoms, charge, multiplicity
            fresh: If True, add NoAutoStart to force fresh calculation
            nprocs: Number of processors (overrides step params)

        Returns:
            ORCA input file content as string
        """
        keywords: Set[str] = set()
        blocks: Dict[str, str] = {}

        # Process SCF root
        scf_params = chain.scf_root.parameters
        self._process_scf_step(chain.scf_root, keywords, blocks)

        # Process downstream steps
        for step in chain.downstream:
            if step.public_type == "td":
                self._process_td_step(step, blocks)
            # Future: freq, nmr, mp2, opt, etc.

        # Add common keywords
        keywords.add("TightSCF")
        if fresh:
            keywords.add("NoAutoStart")

        # Handle nprocs
        effective_nprocs = nprocs or scf_params.get("nprocs")
        if effective_nprocs:
            blocks["pal"] = f"nprocs {effective_nprocs}"

        # Format final input
        return self._format_input(
            chain_key=chain.key,
            keywords=keywords,
            blocks=blocks,
            molecule=molecule,
        )

    def _process_scf_step(
        self,
        step: Any,
        keywords: Set[str],
        blocks: Dict[str, str],
    ) -> None:
        """Process SCF/HF step parameters into keywords and blocks."""
        params = step.parameters

        # Method/functional
        if step.public_type == "hf":
            keywords.add("HF")
        else:
            # DFT functional
            functional = params.get("functional", "B3LYP")
            keywords.add(functional)

        # Basis set
        basis = params.get("basis", "def2-SVP")
        keywords.add(basis)

        # Additional SCF keywords
        if params.get("ri", False):
            keywords.add("RI")
        if params.get("rijcosx", False):
            keywords.add("RIJCOSX")

        # Grid settings
        grid = params.get("grid")
        if grid:
            keywords.add(grid)

        # Dispersion correction
        dispersion = params.get("dispersion")
        if dispersion:
            keywords.add(dispersion)

    def _process_td_step(
        self,
        step: Any,
        blocks: Dict[str, str],
    ) -> None:
        """Process TDDFT step parameters into %tddft block."""
        params = step.parameters

        lines = []
        nroots = params.get("nroots", 5)
        lines.append(f"  NRoots {nroots}")

        tda = params.get("tda", True)
        lines.append(f"  TDA {'true' if tda else 'false'}")

        if "triplets" in params:
            lines.append(f"  Triplets {'true' if params['triplets'] else 'false'}")

        if "maxdim" in params:
            lines.append(f"  MaxDim {params['maxdim']}")

        if "etol" in params:
            lines.append(f"  ETol {params['etol']}")

        if "rtol" in params:
            lines.append(f"  RTol {params['rtol']}")

        blocks["tddft"] = "\n".join(lines)

    def _format_input(
        self,
        chain_key: str,
        keywords: Set[str],
        blocks: Dict[str, str],
        molecule: MoleculeLike,
    ) -> str:
        """Format final ORCA input string."""
        lines: List[str] = []

        # Header comment
        lines.append(f"# Chain: {chain_key}")
        lines.append("# Generated by QMatSuite")
        lines.append("")

        # Keywords line
        keyword_str = " ".join(sorted(keywords))
        lines.append(f"! {keyword_str}")
        lines.append("")

        # PAL block (special single-line format)
        if "pal" in blocks:
            lines.append(f"%pal {blocks['pal']} end")
            lines.append("")

        # Other blocks
        for block_name, block_content in blocks.items():
            if block_name == "pal":
                continue
            lines.append(f"%{block_name}")
            lines.append(block_content)
            lines.append("end")
            lines.append("")

        # Coordinates
        lines.append(f"* xyz {molecule.charge} {molecule.multiplicity}")
        lines.append(molecule.atoms)
        lines.append("*")

        return "\n".join(lines)


def compile_chain_input(
    chain: Any,  # QCChain
    molecule: MoleculeLike,
    fresh: bool = False,
    nprocs: Optional[int] = None,
) -> str:
    """
    Convenience function to compile a chain to ORCA input.

    Args:
        chain: QCChain to compile
        molecule: Molecule object
        fresh: Force fresh calculation (NoAutoStart)
        nprocs: Number of processors

    Returns:
        ORCA input file content
    """
    compiler = ORCAInputCompiler()
    return compiler.compile(chain, molecule, fresh=fresh, nprocs=nprocs)
