meta:
  id: 01KC225VJ5AG52PD3WGCCA7A36
  name: graphene bands
  slug: graphene-bands
  path: workflows/graphene-bands
  kind: workflow
structure: C
mode: normal
working_dir: raw
steps:
- step_id: 01KC226GSW1B35W73WH6KKM3RT
  type: scf
