meta:
  id: 01KB9JA6JSMH7XFZ1AK917TV6J
  name: si-dos
  slug: si-dos
  path: workflows/si-dos
  kind: workflow
structure: si
mode: normal
working_dir: raw
steps:
- id: scf
  step_file: steps/scf.step.yaml
- id: nscf
  step_file: steps/nscf.step.yaml
- id: dos
  step_file: steps/dos.step.yaml
