"""LAMMPS engine input specification for the universal writer.

Two input files: in.lammps (parameters/commands) and structure.data (structure).
"""

from __future__ import annotations

from typing import Any

from quantumvitas.inputformat.core import (
    EngineInputSpec,
    InputFileSpec,
    ResourceRefSpec,
    SSOTMappingSpec,
)


def _write_lammps_script_text(params: dict[str, Any] | None) -> str:
    """Write LAMMPS input script text from parameters.

    Generates a basic LAMMPS input script. Complex scripts use
    Jinja2 templates in the engine; this provides a minimal fallback.
    """
    if not params:
        return ""

    lines: list[str] = []
    lines.append("# LAMMPS input script")
    lines.append("# Generated by QMatSuite")
    lines.append("")

    # Units and dimensions
    lines.append(f"units           {params.get('units', 'metal')}")
    lines.append(f"atom_style      {params.get('atom_style', 'atomic')}")
    lines.append(f"boundary        {params.get('boundary', 'p p p')}")
    lines.append("")

    # Read data
    data_file = params.get("data_file", "structure.data")
    lines.append(f"read_data       {data_file}")
    lines.append("")

    # Pair style
    pair_style = params.get("pair_style", "")
    if pair_style:
        lines.append(f"pair_style      {pair_style}")
        pair_coeff = params.get("pair_coeff", "")
        if pair_coeff:
            lines.append(f"pair_coeff      {pair_coeff}")
        lines.append("")

    # Compute/fix/run parameters
    for key in ("neighbor", "neigh_modify", "fix", "thermo",
                "thermo_style", "timestep", "run", "minimize"):
        val = params.get(key)
        if val is not None:
            lines.append(f"{key:16s}{val}")

    return "\n".join(lines) + "\n"


def _write_lammps_data_text(structure: dict[str, Any] | None) -> str:
    """Write LAMMPS data file text from structure dict.

    Generates a basic LAMMPS data file in 'atomic' style.
    """
    if not structure:
        return ""

    species = structure.get("species", [])
    frac_coords = structure.get("frac_coords", [])
    lattice = structure.get("lattice", [])
    comment = structure.get("comment", "LAMMPS data file")

    unique_species: list[str] = []
    for sp in species:
        if sp not in unique_species:
            unique_species.append(sp)

    n_atoms = len(species)
    n_types = len(unique_species)

    lines: list[str] = []
    lines.append(f"# {comment}")
    lines.append("")
    lines.append(f"{n_atoms} atoms")
    lines.append(f"{n_types} atom types")
    lines.append("")

    # Box bounds (from lattice — assumes orthorhombic for simplicity)
    if lattice:
        ax, ay, az = lattice[0]
        bx, by, bz = lattice[1]
        cx, cy, cz = lattice[2]
        lines.append(f"0.0 {ax:.10f} xlo xhi")
        lines.append(f"0.0 {by:.10f} ylo yhi")
        lines.append(f"0.0 {cz:.10f} zlo zhi")
        # Tilt factors for non-orthorhombic
        if abs(bx) > 1e-10 or abs(cx) > 1e-10 or abs(cy) > 1e-10:
            lines.append(f"{bx:.10f} {cx:.10f} {cy:.10f} xy xz yz")
    lines.append("")

    # Atoms section (atomic style: id type x y z)
    lines.append("Atoms")
    lines.append("")
    for i, (sym, fc) in enumerate(zip(species, frac_coords), 1):
        type_id = unique_species.index(sym) + 1
        # Convert fractional to Cartesian
        if lattice:
            x = fc[0] * lattice[0][0] + fc[1] * lattice[1][0] + fc[2] * lattice[2][0]
            y = fc[0] * lattice[0][1] + fc[1] * lattice[1][1] + fc[2] * lattice[2][1]
            z = fc[0] * lattice[0][2] + fc[1] * lattice[1][2] + fc[2] * lattice[2][2]
        else:
            x, y, z = fc[0], fc[1], fc[2]
        lines.append(f"{i} {type_id} {x:.10f} {y:.10f} {z:.10f}")

    return "\n".join(lines) + "\n"


def get_lammps_input_spec(**context: Any) -> EngineInputSpec:
    """Return the LAMMPS EngineInputSpec."""
    return EngineInputSpec(
        engine_family="lammps",
        syntax_family="command-stream",
        input_files=(
            InputFileSpec(
                filename="in.lammps",
                content_role="parameters",
                description="LAMMPS input script",
                custom_writer=_write_lammps_script_text,
            ),
            InputFileSpec(
                filename="structure.data",
                content_role="structure",
                description="LAMMPS data file (atomic positions)",
                custom_writer=_write_lammps_data_text,
            ),
        ),
        resource_refs=(
            ResourceRefSpec(
                name="potentials",
                description="Force-field potential files (.eam, .tersoff, etc.)",
                staging_policy="copy",
            ),
        ),
        ssot_mapping=SSOTMappingSpec(
            structure_in=("structure.data",),
            params_in=("in.lammps",),
        ),
    )
