"""ABINIT engine input specification for the universal writer.

Single combined file: {step_prefix}.abi containing structure + parameters.
Dynamic filename resolved via get_input_spec(step_prefix=...).
"""

from __future__ import annotations

from typing import Any

from quantumvitas.inputformat.core import (
    EngineInputSpec,
    InputFileSpec,
    ResourceRefSpec,
    SSOTMappingSpec,
)


def _write_abinit_text(fragment: dict[str, Any]) -> str:
    """Write ABINIT input text from combined params + structure.

    Generates flat key-value format. Structure data converted from
    StructureDoc dict to ABINIT variables (acell, rprim, xred, etc.).
    """
    params = fragment.get("params") or {}
    structure = fragment.get("structure") or {}

    lines: list[str] = []
    lines.append("# ABINIT input file")
    lines.append("# Generated by QMatSuite")
    lines.append("")

    # Structure section
    species = structure.get("species", [])
    frac_coords = structure.get("frac_coords", [])
    lattice = structure.get("lattice", [])

    if species:
        unique_species: list[str] = []
        for sp in species:
            if sp not in unique_species:
                unique_species.append(sp)

        lines.append(f"natom  {len(species)}")
        lines.append(f"ntypat {len(unique_species)}")

        # typat: type index for each atom
        typat = [unique_species.index(sp) + 1 for sp in species]
        lines.append(f"typat  {' '.join(str(t) for t in typat)}")

        # znucl: atomic numbers (simplified — use placeholder)
        znucl_map = params.get("znucl", {})
        znucl_vals = []
        for sp in unique_species:
            znucl_vals.append(str(znucl_map.get(sp, 0)))
        lines.append(f"znucl  {' '.join(znucl_vals)}")
        lines.append("")

    if lattice:
        # Use acell + rprim
        lines.append("acell  1.0 1.0 1.0  Angstrom")
        lines.append("rprim")
        for vec in lattice:
            lines.append(f"  {vec[0]:.10f}  {vec[1]:.10f}  {vec[2]:.10f}")
        lines.append("")

    if frac_coords:
        lines.append("xred")
        for fc in frac_coords:
            lines.append(f"  {fc[0]:.10f}  {fc[1]:.10f}  {fc[2]:.10f}")
        lines.append("")

    # Calculation parameters
    skip_keys = {"znucl", "pseudo", "pseudos", "pp_dirpath"}
    for key, val in sorted(params.items()):
        if key in skip_keys:
            continue
        if isinstance(val, (list, tuple)):
            val_str = " ".join(str(v) for v in val)
        elif isinstance(val, bool):
            val_str = "1" if val else "0"
        elif isinstance(val, dict):
            continue  # Skip nested dicts
        else:
            val_str = str(val)
        lines.append(f"{key}  {val_str}")

    # Pseudopotential references
    pseudos = params.get("pseudos", [])
    pp_dirpath = params.get("pp_dirpath", "./")
    if pseudos:
        lines.append("")
        lines.append(f'pp_dirpath "{pp_dirpath}"')
        lines.append(f'pseudos "{", ".join(pseudos)}"')

    return "\n".join(lines) + "\n"


def get_abinit_input_spec(**context: Any) -> EngineInputSpec:
    """Return the ABINIT EngineInputSpec.

    Args:
        **context: May contain step_prefix for dynamic filename.
    """
    step_prefix = context.get("step_prefix", "run")
    filename = f"{step_prefix}.abi"

    return EngineInputSpec(
        engine_family="abinit",
        syntax_family="flat-keyval",
        input_files=(
            InputFileSpec(
                filename=filename,
                content_role="combined",
                description="ABINIT input file",
                custom_writer=_write_abinit_text,
            ),
        ),
        resource_refs=(
            ResourceRefSpec(
                name="pseudopotentials",
                description="ABINIT pseudopotential files",
                staging_policy="reference",
            ),
        ),
        ssot_mapping=SSOTMappingSpec(
            structure_in=(filename,),
            kpoints_in=(filename,),
            params_in=(filename,),
        ),
    )
