"""ABINIT engine input specification for the universal writer.

Single combined file: {step_prefix}.abi containing structure + parameters.
Dynamic filename resolved via get_input_spec(step_prefix=...).
"""

from __future__ import annotations

from typing import Any

from quantumvitas.inputformat.core import (
    EngineInputSpec,
    InputFileSpec,
    ResourceRefSpec,
    SSOTMappingSpec,
)


def _write_abinit_text(fragment: dict[str, Any]) -> str:
    """Write ABINIT input text from combined params + structure.

    Generates flat key-value format. Structure data converted from
    StructureDoc dict to ABINIT variables (acell, rprim, xred, etc.).
    """
    params = fragment.get("params") or {}
    structure = fragment.get("structure") or {}

    lines: list[str] = []
    lines.append("# ABINIT input file")
    lines.append("# Generated by QMatSuite")
    lines.append("")

    # Structure section
    species = structure.get("species", [])
    frac_coords = structure.get("frac_coords", [])
    lattice = structure.get("lattice", [])

    if species:
        unique_species: list[str] = []
        for sp in species:
            if sp not in unique_species:
                unique_species.append(sp)

        lines.append(f"natom  {len(species)}")
        lines.append(f"ntypat {len(unique_species)}")

        # typat: type index for each atom
        typat = [unique_species.index(sp) + 1 for sp in species]
        lines.append(f"typat  {' '.join(str(t) for t in typat)}")

        # znucl: atomic numbers (simplified — use placeholder)
        znucl_map = params.get("znucl", {})
        znucl_vals = []
        for sp in unique_species:
            znucl_vals.append(str(znucl_map.get(sp, 0)))
        lines.append(f"znucl  {' '.join(znucl_vals)}")
        lines.append("")

    if lattice:
        # Use acell + rprim
        lines.append("acell  1.0 1.0 1.0  Angstrom")
        lines.append("rprim")
        for vec in lattice:
            lines.append(f"  {vec[0]:.10f}  {vec[1]:.10f}  {vec[2]:.10f}")
        lines.append("")

    if frac_coords:
        lines.append("xred")
        for fc in frac_coords:
            lines.append(f"  {fc[0]:.10f}  {fc[1]:.10f}  {fc[2]:.10f}")
        lines.append("")

    # Calculation parameters
    skip_keys = {"znucl", "pseudo", "pseudos", "pp_dirpath"}
    for key, val in sorted(params.items()):
        if key in skip_keys:
            continue
        if isinstance(val, (list, tuple)):
            val_str = " ".join(str(v) for v in val)
        elif isinstance(val, bool):
            val_str = "1" if val else "0"
        elif isinstance(val, dict):
            continue  # Skip nested dicts
        else:
            val_str = str(val)
        lines.append(f"{key}  {val_str}")

    # Pseudopotential references
    pseudos = params.get("pseudos", [])
    pp_dirpath = params.get("pp_dirpath", "./")
    if pseudos:
        lines.append("")
        lines.append(f'pp_dirpath "{pp_dirpath}"')
        lines.append(f'pseudos "{", ".join(pseudos)}"')

    return "\n".join(lines) + "\n"


# Atomic number → symbol for the first 103 elements (znucl reversal)
_ATOMIC_SYMBOLS = [
    "",  # 0 placeholder
    "H", "He", "Li", "Be", "B", "C", "N", "O", "F", "Ne",
    "Na", "Mg", "Al", "Si", "P", "S", "Cl", "Ar",
    "K", "Ca", "Sc", "Ti", "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn",
    "Ga", "Ge", "As", "Se", "Br", "Kr",
    "Rb", "Sr", "Y", "Zr", "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag", "Cd",
    "In", "Sn", "Sb", "Te", "I", "Xe",
    "Cs", "Ba", "La", "Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd", "Tb", "Dy",
    "Ho", "Er", "Tm", "Yb", "Lu",
    "Hf", "Ta", "W", "Re", "Os", "Ir", "Pt", "Au", "Hg",
    "Tl", "Pb", "Bi", "Po", "At", "Rn",
    "Fr", "Ra", "Ac", "Th", "Pa", "U", "Np", "Pu", "Am", "Cm", "Bk", "Cf",
    "Es", "Fm", "Md", "No", "Lr",
]


def _parse_abinit_text(text: str) -> dict[str, Any]:
    """Parse ABINIT input text into combined params + structure dict.

    Handles:
    - key value lines (whitespace separated)
    - Comments (# and !)
    - Multi-line arrays (xred, rprim — data lines continue previous key)
    - Structure variables: natom, ntypat, typat, znucl, acell, rprim, xred
    - Pseudopotential references (pp_dirpath, pseudos)

    Returns:
        {"params": {...}, "structure": {...}} matching writer input format.
    """
    raw_data: dict[str, list[str]] = {}
    current_key: str | None = None

    for raw_line in text.splitlines():
        # Strip comments
        line = raw_line.split("#")[0].split("!")[0].strip()
        if not line:
            current_key = None
            continue

        # Check if line starts with a keyword (alphabetic first character)
        tokens = line.split()
        if tokens[0][0].isalpha() or tokens[0][0] == '"':
            # New key-value pair
            current_key = tokens[0]
            if current_key not in raw_data:
                raw_data[current_key] = []
            raw_data[current_key].extend(tokens[1:])
        elif current_key is not None:
            # Continuation of previous key (numeric data)
            raw_data[current_key].extend(tokens)
        # else: orphan numeric line, skip

    # Separate structure keys from params
    structure_keys = {"natom", "ntypat", "typat", "znucl", "acell", "rprim", "xred"}
    pseudo_keys = {"pp_dirpath", "pseudos"}

    params: dict[str, Any] = {}
    struct_raw: dict[str, list[str]] = {}

    for key, vals in raw_data.items():
        if key in structure_keys:
            struct_raw[key] = vals
        elif key in pseudo_keys:
            # Quoted values: join and strip quotes
            joined = " ".join(vals).strip('"')
            params[key] = joined
        else:
            params[key] = _coerce_abinit_value(vals)

    # Reconstruct structure dict
    structure = _reconstruct_structure(struct_raw)

    # Store znucl mapping in params for roundtrip
    if "znucl" in struct_raw and structure.get("species"):
        unique_species: list[str] = []
        for sp in structure["species"]:
            if sp not in unique_species:
                unique_species.append(sp)
        znucl_vals = [int(float(v)) for v in struct_raw["znucl"]]
        znucl_map = {}
        for sp, z in zip(unique_species, znucl_vals):
            znucl_map[sp] = z
        params["znucl"] = znucl_map

    return {"params": params, "structure": structure}


def _coerce_abinit_value(vals: list[str]) -> Any:
    """Coerce a list of string tokens from ABINIT input to Python types."""
    if len(vals) == 0:
        return ""

    # Handle unit suffix on single-value lines (e.g., "1.0d-8" or "30")
    # Filter out known unit strings
    known_units = {"Angstrom", "Bohr", "eV", "Ha", "Ry", "angstrom", "bohr"}
    filtered = [v for v in vals if v not in known_units]

    if len(filtered) == 0:
        return " ".join(vals)

    if len(filtered) == 1:
        return _coerce_abinit_single(filtered[0])

    # Multi-value: try to coerce all to numbers
    coerced = [_coerce_abinit_single(v) for v in filtered]
    all_numeric = all(isinstance(v, (int, float)) for v in coerced)
    if all_numeric:
        return coerced
    return " ".join(vals)


def _coerce_abinit_single(s: str) -> Any:
    """Coerce a single ABINIT token."""
    s = s.strip().strip('"')
    if not s:
        return s

    # Handle Fortran d exponent
    lower = s.lower()
    if "d" in lower and not lower.startswith("d"):
        try:
            return float(lower.replace("d", "e"))
        except ValueError:
            pass

    if "." in s or "e" in s.lower():
        try:
            return float(s)
        except ValueError:
            pass

    try:
        return int(s)
    except ValueError:
        pass

    return s


def _reconstruct_structure(struct_raw: dict[str, list[str]]) -> dict[str, Any]:
    """Reconstruct StructureDoc dict from ABINIT structure variables."""
    structure: dict[str, Any] = {}

    # Lattice: rprim (3x3 matrix) scaled by acell
    if "rprim" in struct_raw:
        rprim_vals = [float(v) for v in struct_raw["rprim"]]
        if len(rprim_vals) >= 9:
            lattice = [
                [rprim_vals[0], rprim_vals[1], rprim_vals[2]],
                [rprim_vals[3], rprim_vals[4], rprim_vals[5]],
                [rprim_vals[6], rprim_vals[7], rprim_vals[8]],
            ]
            structure["lattice"] = lattice

    # Fractional coordinates: xred
    if "xred" in struct_raw:
        xred_vals = [float(v) for v in struct_raw["xred"]]
        natom = len(xred_vals) // 3
        frac_coords = []
        for i in range(natom):
            frac_coords.append([
                xred_vals[3 * i],
                xred_vals[3 * i + 1],
                xred_vals[3 * i + 2],
            ])
        structure["frac_coords"] = frac_coords

    # Species: znucl + typat → element symbols
    if "znucl" in struct_raw and "typat" in struct_raw:
        znucl = [int(float(v)) for v in struct_raw["znucl"]]
        typat = [int(float(v)) for v in struct_raw["typat"]]
        species = []
        for t in typat:
            z = znucl[t - 1] if 1 <= t <= len(znucl) else 0
            if 0 < z < len(_ATOMIC_SYMBOLS):
                species.append(_ATOMIC_SYMBOLS[z])
            else:
                species.append(f"Type{t}")
        structure["species"] = species

    return structure


def get_abinit_input_spec(**context: Any) -> EngineInputSpec:
    """Return the ABINIT EngineInputSpec.

    Args:
        **context: May contain step_prefix for dynamic filename.
    """
    step_prefix = context.get("step_prefix", "run")
    filename = f"{step_prefix}.abi"

    return EngineInputSpec(
        engine_family="abinit",
        syntax_family="flat-keyval",
        input_files=(
            InputFileSpec(
                filename=filename,
                content_role="combined",
                description="ABINIT input file",
                custom_writer=_write_abinit_text,
                custom_parser=_parse_abinit_text,
            ),
        ),
        resource_refs=(
            ResourceRefSpec(
                name="pseudopotentials",
                description="ABINIT pseudopotential files",
                staging_policy="reference",
            ),
        ),
        ssot_mapping=SSOTMappingSpec(
            structure_in=(filename,),
            kpoints_in=(filename,),
            params_in=(filename,),
        ),
    )
