meta:
  id: 01KC2PAM46ETTT1M3CX4HH0YTC
  name: Si dos
  slug: si-dos
  path: workflows/si-dos
  kind: workflow
structure: si
mode: normal
working_dir: raw
steps:
- step_id: 01KC2PBHT13P2EC9NAP34X4WZQ
  type: scf
