meta:
  id: 01KC0WCFZC8V3QN8BP2SBHJ181
  name: graphene bands
  slug: graphene-bands
  path: workflows/graphene-bands
  kind: workflow
structure: C
mode: normal
working_dir: raw
steps:
- id: scf
  step_file: steps/scf.step.yaml
- id: bands_pw
  step_file: steps/bands_pw.step.yaml
- id: bands
  step_file: steps/bands.step.yaml
